name: libphonenumber
description: A new flutter plugin project.
version: 0.0.1
author: LoremIpsum
homepage: LoremIpsum

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  
  libphonenumber_platform_interface:
    path: ../libphonenumber_platform_interface

  libphonenumber_web:
    path: ../libphonenumber_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        default_package: libphonenumber_web
